name: CI
on:
  merge_group:
  push:
    branches:
      - main
    tags: ['*']
  pull_request:
concurrency:
  # Skip intermediate builds: always.
  # Cancel intermediate builds: only if it is a pull request build.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}
permissions:
  contents: read
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1'
          - '1.6'
        os:
          - ubuntu-latest
          - windows-latest
          - macos-26-intel # macOS on Intel (x86_64)
          - macos-latest # macOS on Apple Silicon (aarch64)
        exclude:
          # Julia 1.6 does not have a native macOS aarch64 build
          - version: '1.6'
            os: macos-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: julia-actions/setup-julia@fa02766e078afaaf09b14210362cee14137e6a32 # v3.0.2
        with:
          version: ${{ matrix.version }}
      - uses: julia-actions/julia-buildpkg@e3eb439fad4f9aba7da2667e7510e4a46ebc46e1 # v1.7.0
      - uses: julia-actions/julia-runtest@6e050c8013b833b1195105ff2fce9cd802f53271 # v1.12.0
  docs:
    name: Documentation
    permissions:
      contents: write
      statuses: write
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: julia-actions/setup-julia@fa02766e078afaaf09b14210362cee14137e6a32 # v3.0.2
        with:
          version: '1'
      - name: Install dependencies
        run: julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
      - name: Build and deploy
        env:
          JULIA_DEBUG: Documenter
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: julia --project=docs/ docs/make.jl
  finalize:
    name: CI result
    runs-on: ubuntu-latest
    if: always()
    needs: [test, docs]
    steps:
      - run: |
          results='${{ toJSON(needs.*.result) }}'
          echo "Job results: $results"
          if echo "$results" | grep -qE '"(failure|cancelled)"'; then
            echo "Some required jobs failed or were cancelled"
            exit 1
          fi
